const ADD_NAME = 'ADD_NAME';
const ADD_EMAIL = 'ADD_EMAIL';
const ADD_CPF = 'ADD_CPF';
const ADD_ADDRESS = 'ADD_ADDRESS';
const ADD_CITY = 'ADD_CITY';
const ADD_STATE = 'ADD_STATE';
const ADD_HOUSE = 'ADD_HOUSE';
const ADD_SUMMARY = 'ADD_SUMMARY';
const ADD_JOB = 'ADD_JOB';
const ADD_JOBDESCRIPTION = 'ADD_JOBDESCRIPTION';

export {
  ADD_NAME,
  ADD_EMAIL,
  ADD_CPF,
  ADD_ADDRESS,
  ADD_CITY,
  ADD_STATE,
  ADD_HOUSE,
  ADD_SUMMARY,
  ADD_JOB,
  ADD_JOBDESCRIPTION,
}
